### ISSUE TITLE
Works but documentation and help inadequate

### ISSUE THREAD

**Issue by PacoH** [fenhl/webloc-cli#3]
Works but documentation and help inadequate
-----------------------------------------------------------------------------------------------------------------------------
```
$ webloc -h
webloc-cli 1.1.1

USAGE:
    webloc <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    help    Print this message or the help of the given subcommand(s)
    read    Output the URL contained in a webloc file
    save    Store a URL in a webloc file
```

**README.md**

```
webloc read [<filename>]
webloc save [<filename>] [<url>]

The --xml (or -x) flag can be passed to make webloc output a human-readable XML webloc file instead of using the more compact binary format.
```

Tried:
```
webloc --xml save "title.webloc" "url"

error: Found argument '--xml' which wasn't expected, or isn't valid in this context

	Did you mean to put '--xml' after the subcommand 'save'?

	If you tried to supply `--xml` as a value rather than a flag, use `-- --xml`

USAGE:
    webloc <SUBCOMMAND>
```

Worked:
`webloc save --xml "title.webloc" "url"`

Had to specify `.webloc`. `filename` usually means just the name. `file` would mean `filename.extension`. `.webloc` should be appended to `filename` by default as that is what you get when you drag the url to a Finder folder.

**Comment by fenhl** [comment]
There seem to be 2 separate issues here:

1. The requirement for a subcommand's options to be listed after the subcommand. This is a non-configurable behavior of the command-line parsing library I am using ([`clap`](https://docs.rs/clap)), and it matches the behavior of other CLIs with subcommands, such as `git`. I have clarified in the readme that the `--xml` flag only applies to the `save` subcommand. Other than that, I don't think any action is required, since the error message printed on the command line does suggest the correct invocation.
2. The ability to omit the `.webloc` extension. I don't think this is a good idea since the `<filename>` argument is actually a _path_. I think it would be unexpected for a command-line tool like this to silently append a file extension to a path. I have renamed the argument and clarified this in the readme though.

While I haven't implemented either of your suggestions for changing the CLI's behavior, hopefully these documentation changes address the usability concerns. If you have any further suggestions for improving other parts of the documentation or help, please open them as separate issues.
